### ISSUE TITLE
Cannot read property 'compilation' of undefined

### ISSUE THREAD

**Issue by yasserzubair** [nerdmax/html-webpack-change-assets-extension-plugin#18]
working with webpack 3.10.0, whenever i build i get this error

`TypeError: Cannot read property 'compilation' of undefined
    at HtmlWebpackChangeAssetsExtensionPlugin.apply (/Users/yasserzubair1/projects/graana-projects/node_modules/html-webpack-change-assets-extension-plugin/dist/html-webpack-change-assets-extension-plugin.umd.js:13:26)
    at Compiler.apply (/Users/yasserzubair1/projects/graana-projects/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/yasserzubair1/projects/graana-projects/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/Users/yasserzubair1/projects/graana-projects/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/Users/yasserzubair1/projects/graana-projects/node_modules/webpack/bin/webpack.js:397:2)
    at Object.Yargs.self.parse (/Users/yasserzubair1/projects/graana-projects/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/Users/yasserzubair1/projects/graana-projects/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3`
what's wrong?

**Comment by nerdmax** [comment]
Thank you for reporting this issue. Unfortunately, this lib only supports webpack@4 with html-webpack-plugin@3/@4. Normally, a webpack plugin is only compatible with webpack@3 or webpack@4. Eg: [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/360)

I suggest you upgrade your webapck to v4. It has been released for almost a year.

**Comment by yasserzubair** [comment]
Thanks, though i think it must be mentioned somwhere in the docs that it only works with webpack 4
