### ISSUE TITLE
webpack@4.5 TypeError: Cannot read property 'tapAsync' of undefined

### ISSUE THREAD

**Issue by garyvh2** [nerdmax/html-webpack-change-assets-extension-plugin#7]
```
              compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tapAsync('HtmlWebpackChangeAssetsExtensionPlugin', function (data, cb) {
                                                                      ^

TypeError: Cannot read property 'tapAsync' of undefined
    at C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\html-webpack-change-assets-extension-plugin\dist\html-webpack-change-assets-extension-plugin.umd.js:13:71
    at SyncHook.eval [as call] (eval at create (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack\lib\Compiler.js:503:26)
    at hooks.beforeCompile.callAsync.err (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack\lib\Compiler.js:539:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack\lib\Compiler.js:534:28)
    at readRecords.err (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack\lib\Compiler.js:274:11)
    at Compiler.readRecords (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack\lib\Compiler.js:401:11)
    at hooks.run.callAsync.err (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack\lib\Compiler.js:271:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack\lib\Compiler.js:268:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.run (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack\lib\Compiler.js:265:24)
    at processOptions (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack-cli\bin\cli.js:533:20)
    at yargs.parse (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack-cli\bin\cli.js:536:3)
    at Object.parse (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\yargs\yargs.js:563:18)
    at C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack-cli\bin\cli.js:538:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Projects\BDX\bdxliveredesign\BdxRedesign.App\node_modules\webpack\bin\webpack.js:155:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

This was solved in `html-webpack-include-assets-plugin` through the following commit https://github.com/jharris4/html-webpack-include-assets-plugin/commit/b12d05a8d699f9a3045f4531118f9eea16ee3826#diff-168726dbe96b3ce427e7fedce31bb0bcR355

I'll submit a pull request

**Comment by nerdmax** [comment]
Thank you for addressing this issue. Looking forward to your pull request!:)

**Comment by garyvh2** [comment]
```
const HtmlWebpackPlugin = require('html-webpack-plugin')

export default class HtmlWebpackChangeAssetsExtensionPlugin {
  options: object

  constructor(options?: object) {
    this.options = options || {}
  }

  apply(compiler: any) {
    compiler.hooks.compilation.tap('HtmlWebpackChangeAssetsExtensionPlugin', (compilation: any) => {
      let beforeGenerationHook
      if (compilation.hooks.htmlWebpackPluginBeforeHtmlGeneration) {
        // Webpack 3.x
        const { hooks } = compilation
        beforeGenerationHook = hooks.htmlWebpackPluginBeforeHtmlGeneration
      } else if (HtmlWebpackPlugin.version === 4) {
        // Webpack 4.x
        const hooks = HtmlWebpackPlugin.getHooks(compilation)
        beforeGenerationHook = hooks.beforeAssetTagGeneration
      } else {
        return
      }
      beforeGenerationHook.tapAsync(
        'HtmlWebpackChangeAssetsExtensionPlugin',
        (data: any, cb: Function) => {
          // Skip if the plugin configuration didn't set `jsExtension`
          if (!data.plugin.options.jsExtension) {
            return cb(null)
          }
          const jsExtension = data.plugin.options.jsExtension
          const tempArray = data.assets.js
          data.assets.js = tempArray.map((scriptFile: any) => `${scriptFile}${jsExtension}`)
          return cb(null, data)
        }
      )
    })
  }
}
```

This is a possible fix, I was wondering if you had any idea on how to provide test for this, as it would fail coverage testing due to all branches not being covered.

**Comment by nerdmax** [comment]
That's a good question... I think I need to do some research about that.

**Comment by nerdmax** [comment]
PS: I've tried with webpack@4.5, webpack@4.21, webpack@4.25.1(The latest one) and all of them are working fine.

Can you please provide the webpack's version that you are using?

**Comment by garyvh2** [comment]
Exact problem is with `webpack@4.5` and `html-webpack-plugin@4.0.0.beta-4`

Just confirmed.

**Comment by nerdmax** [comment]
Cool! I will try to resolve this issue with `html-webpack-plugin@4.0.0.beta-4`.

Also thank you for that joliss/node-multidep suggestion!

**Comment by nerdmax** [comment]
@garyvh2, sorry I tried [joliss/node-multidep](https://github.com/joliss/node-multidep) but it doesn't work. I guess it because even though we can use different versions of `html-webpack-plugin` in test, the `html-webpack-plugin` that this plugin required is still from the project's node_modules. I ended up just reduce the `coverageThreshold` of this project.

Please let me know if you have any other better solutions.

Big thanks to your contribution!

**Comment by garyvh2** [comment]
Yeah, I tried for some hours to make it work, but it simply doesn't.

It's really weird.

**Comment by nerdmax** [comment]
@garyvh2 The latest version [1.0.1](https://www.npmjs.com/package/html-webpack-change-assets-extension-plugin) has been released.

**Comment by garyvh2** [comment]
@nerdmax Thank you so much

**Comment by nerdmax** [comment]
@garyvh2 I've found a workaround to fix the test coverage issue. It will also make the tests more solid. You can check the latest several commits if you want to know how I fix that. Feel free to leave any comments.

I really appreciate your help and I've added you as one of the contributors of this project in README file without your permission. Please do let me know if you think it's inappropriate.

PS: I also fixed some bugs of this library and pushed ad new release ([1.0.2](https://www.npmjs.com/package/html-webpack-change-assets-extension-plugin))

**Comment by garyvh2** [comment]
@nerdmax Awesome, I'll have a look, good to know you were able to fix it.

Thank you so much

**Comment by pimvanderheijden** [comment]
Is it me or is this simply broken with webpack v5? I placed a comment in the "compression-webpack-plugin" repo about this but no response so far. Copying my remark here, see what you guys think about it. Apologies if it does work and I missed something.

I'm running:
```
node --trace-deprecation node_modules/webpack/bin/webpack.js --config ./webpack-configs/webpack.prod-client.js
```

I'm getting:

[webpack-cli] TypeError: Cannot read property 'tapAsync' of undefined                                                                                                                                              
    at ... /node_modules/html-webpack-change-assets-extension-plugin/dist/html-webpack-change-assets-extension-plugin.umd.js:25:36
   
Node 14
Webpack v5
html-webpack-change-assets-extension-plugin 1.2.0
html-webpack-plugin 5.3.2

In html-webpack-plugin jsExtension seems to be deprecated, it doesn't appear to do anything and it's not in the docs.
Other than I've nothing worth mentioning in my html-webpack-plugin definition.
Also changing the order of creating the plugins does not change a thing.

This is my webpack config by the way:

```
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const CompressionPlugin = require('compression-webpack-plugin')
const HtmlWebpackChangeAssetsExtensionPlugin = require('html-webpack-change-assets-extension-plugin')

module.exports = {
    mode   : 'production',
    target : 'web',
    output: {
        filename      : '[name]-bundle.[fullhash].js',
        chunkFilename : '[name].js',
        path          : path.resolve(__dirname, '../build/'),
        publicPath    : '/'
    },
    plugins: [
        new HtmlWebpackPlugin({
            template           : 'index.pug',
            jsExtension        : '.gz',
        }),
        new CompressionPlugin({
            test: /\.(js|css|html|svg|png|gif|jpg|woff|woff2|eot|ttf|otf)$/
        }),
        new HtmlWebpackChangeAssetsExtensionPlugin()
    ]
}
```
